// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LeTest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void leTest1() {
    driver.get("https://www.le.com/");
    driver.manage().window().setSize(new Dimension(866, 1073));
    {
      WebElement element = driver.findElement(By.cssSelector(".focus_list li:nth-child(1) > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("电影")).click();
    vars.put("win6006", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6006").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".nav_box2 .curr")).click();
    vars.put("win3153", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3153").toString());
    driver.findElement(By.linkText("免费")).click();
    driver.findElement(By.linkText("动作")).click();
    driver.findElement(By.linkText("中国香港")).click();
    driver.findElement(By.linkText("2016")).click();
    driver.findElement(By.linkText("最新")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".videoBox:nth-child(1) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//img[@alt=\'赏金猎人\']")).click();
    vars.put("win6182", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win6182").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".j-juji-recommend i"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("wd")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".search_btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("wd")).sendKeys("周星驰");
    driver.findElement(By.cssSelector(".search_btn")).click();
    driver.findElement(By.cssSelector(".channel_home > .icon_text")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("电视剧")).click();
    vars.put("win5138", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5138").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("更多")).click();
    vars.put("win1590", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1590").toString());
    driver.findElement(By.linkText("独播")).click();
    driver.findElement(By.linkText("穿越")).click();
    driver.findElement(By.linkText("2013")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".imagePart > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".imagePart > img")).click();
    vars.put("win9151", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win9151").toString());
    driver.findElement(By.linkText("花絮")).click();
    driver.findElement(By.linkText("分集剧情")).click();
    driver.findElement(By.linkText("乐迷畅谈")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h2 > em"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
