// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Default0Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void default0() {
    driver.get("http://localhost:8080/mtours/servlet/WelcomeServlet");
    driver.manage().window().setSize(new Dimension(1051, 797));
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("123");
    {
      String value = driver.findElement(By.name("userName")).getAttribute("value");
      assertThat(value, is("123"));
    }
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector("font:nth-child(1) > input:nth-child(2)")).click();
    driver.findElement(By.name("tripType")).click();
    {
      String value = driver.findElement(By.name("tripType")).getAttribute("value");
      assertThat(value, is("roundtrip"));
    }
    driver.findElement(By.name("findFlights")).click();
    driver.findElement(By.name("reserveFlights")).click();
    driver.findElement(By.name("passFirst0")).click();
    driver.findElement(By.name("passFirst0")).sendKeys("456");
    driver.findElement(By.name("passLast0")).click();
    driver.findElement(By.name("passLast0")).sendKeys("789");
    driver.findElement(By.name("creditnumber")).click();
    driver.findElement(By.name("creditnumber")).sendKeys("123");
    driver.findElement(By.name("delCountry")).click();
    {
      WebElement dropdown = driver.findElement(By.name("delCountry"));
      dropdown.findElement(By.xpath("//option[. = 'TOGO']")).click();
    }
    {
      WebElement element = driver.findElement(By.name("delCountry"));
      String value = element.getAttribute("value");
      String locator = String.format("option[@value='%s']", value);
      String selectedText = element.findElement(By.xpath(locator)).getText();
      assertThat(selectedText, is("TOGO"));
    }
    assertThat(driver.switchTo().alert().getText(), is("You have chosen a mailing location outside of the United States and its territories. An additional charge of $6.5 will be added as mailing charge."));
    driver.findElement(By.name("buyFlights")).click();
    driver.findElement(By.cssSelector("tr:nth-child(7) td:nth-child(2) img")).click();
    driver.close();
  }
}
